server:
  servlet:
    context-path: /community

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/community?serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.castor6.community.bean

pagehelper:
  helper-dialect: mysql
  reasonable: true

